id: d9aff663f4ca47daabfde72a900d045c
initial_creation_type: TMX
origin_type: translation
source_metadata:
  id: ''
  title: Toh_114-The_King_of_the_Array_of_All_Dharmas-v1
  language: bo
  author: ''
  volume: {}
